### ISSUE TITLE
Task List 10/8

### ISSUE THREAD

**Issue by jork41989** [jork41989/cumulusNote#4]
- [x] style menu bar

- [x] set up modal for sign up / sign in

- [x]  pick temp logo

**Comment by jork41989** [comment]
Added all, waiting for review
